### ISSUE TITLE
Is there any guide or demos about creating Privileged Enclaves (P-Enclave) and Host User Enclaves (HU-Enclave)?

### ISSUE THREAD

**Issue by bronzeMe** [HyperEnclave/hyperenclave#17]
Following the paper's statements in [Section 4, Flexible Enclave Operation Mode](https://www.usenix.org/system/files/atc22-jia-yuekai.pdf), HyperEnclave supports the creation of flexible enclaves. Could you please provide some guides or demos to present this feature?

**Comment by Bonjourz** [comment]
Hi, @bronzeMe, we have shown how to reproduce evaluation result stated in the paper, see the "Artifact Appendix" section in the [paper](https://www.usenix.org/system/files/atc22-jia-yuekai.pdf) for details.

**Comment by bronzeMe** [comment]
@Bonjourz By the way, is there any demos about performing remote attestation?

**Comment by Bonjourz** [comment]
Hi @bronzeMe , in current production environment, HyperEnclave's remote attestation relies on some infrastructure service from Ant Group, so its demo has not been published under our decision.

Could you please show what is the your purpose of trying remote attestation? What is the scenarios in your case? Let us  take look that whether we can provide some assistance for your case.

**Comment by bronzeMe** [comment]
@Bonjourz Hi, we recently plan to deploy HyperEnclave on the Hygon hardware platform and test the entire process, including the measurement calculation during the offline phase, TPM trusted boot during the startup phase, and remote attestation during the runtime phase. Our goal is to successfully complete the entire process and eventually make it practical for use in products.

**Comment by bronzeMe** [comment]
@Bonjourz Hi, How do we perform a remote attestation demo using a fake TPM? Could you give some tips? Thanks.

**Comment by bronzeMe** [comment]
Is the source code for [libtpm.a](https://github.com/HyperEnclave/hyperenclave/blob/master/lib/libtpm.a) available?

**Comment by Bonjourz** [comment]
> Is the source code for [libtpm.a](https://github.com/HyperEnclave/hyperenclave/blob/master/lib/libtpm.a) available?

Hi @bronzeMe , currently the libtpm's source code is not open-sourced.

**Comment by bronzeMe** [comment]
> @Bonjourz Hi, How do we perform a remote attestation demo using a fake TPM? Could you give some tips? Thanks.

@Bonjourz About this question, could you provide some suggestions？

**Comment by Bonjourz** [comment]
> > @Bonjourz Hi, How do we perform a remote attestation demo using a fake TPM? Could you give some tips? Thanks.
> 
> @Bonjourz About this question, could you provide some suggestions？

Hi @bronzeMe , as discussed on the meeting, we are now working to provide FAKE Remote attestation demo equipped with fake TPM. If all goes well, the demo will be available next week 😁.

**Comment by bronzeMe** [comment]
@Bonjourz Thanks! 
By the way, are the source codes of the patches for both Intel SGX SDK and RUST SGX SDK available? We did not find them.

**Comment by Bonjourz** [comment]
> @Bonjourz Thanks! By the way, are the source codes of the patches for both Intel SGX SDK and RUST SGX SDK available? We did not find them.

Hi @bronzeMe , they are not available now. We are considering whether to open source them. If there are any updates, we will show them on [README](https://github.com/HyperEnclave/hyperenclave/blob/master/README.md).

**Comment by Bonjourz** [comment]
> @Bonjourz Thanks! By the way, are the source codes of the patches for both Intel SGX SDK and RUST SGX SDK available? We did not find them.

Hi @bronzeMe , we have updated Fake Remote Attestation demo. See [README.md](https://github.com/HyperEnclave/hyperenclave/blob/master/demos/RemoteAttestation/README.md) in demos/RemoteAttestation.

**Comment by bronzeMe** [comment]
@Bonjourz Thanks !! we try it now.

**Comment by bronzeMe** [comment]
> > @Bonjourz Thanks! By the way, are the source codes of the patches for both Intel SGX SDK and RUST SGX SDK available? We did not find them.
> 
> Hi @bronzeMe , we have updated Fake Remote Attestation demo. See [README.md](https://github.com/HyperEnclave/hyperenclave/blob/master/demos/RemoteAttestation/README.md) in demos/RemoteAttestation.

@Bonjourz Hi,  the function ` ret = sgx_verify_quote((uint8_t*)p_isv_quote, QUOTE_SIZE, report_data, report_data_len, &cert_chain);` implemented inside hyperenclave SDK perform the specific TPM-quote-based attestation operations, is it right?

Q1： When will this function be open source?
Q2 What is the detailed difference about performing attestation between NO_CA mode and CA mode?

<img width="1520" alt="image" src="https://github.com/user-attachments/assets/4d883ab1-776b-43d3-917f-62bb78672935">

**Comment by Bonjourz** [comment]
> > > @Bonjourz Thanks! By the way, are the source codes of the patches for both Intel SGX SDK and RUST SGX SDK available? We did not find them.
> > 
> > 
> > Hi @bronzeMe , we have updated Fake Remote Attestation demo. See [README.md](https://github.com/HyperEnclave/hyperenclave/blob/master/demos/RemoteAttestation/README.md) in demos/RemoteAttestation.
> 
> @Bonjourz Hi, the function ` ret = sgx_verify_quote((uint8_t*)p_isv_quote, QUOTE_SIZE, report_data, report_data_len, &cert_chain);` implemented inside hyperenclave SDK perform the specific TPM-quote-based attestation operations, is it right?
> 
> Q1： When will this function be open source? Q2 What is the detailed difference about performing attestation between NO_CA mode and CA mode?
> 
> <img alt="image" width="1520" src="https://private-user-images.githubusercontent.com/11402109/357426965-4d883ab1-776b-43d3-917f-62bb78672935.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjM2ODY0MDIsIm5iZiI6MTcyMzY4NjEwMiwicGF0aCI6Ii8xMTQwMjEwOS8zNTc0MjY5NjUtNGQ4ODNhYjEtNzc2Yi00M2QzLTkxN2YtNjJiYjc4NjcyOTM1LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODE1VDAxNDE0MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzNDM1N2ZhOGFmODhjZWVhNzFkZWFjYjlmMTE0NzllNTlmZTM4NDUzNmY1ZDIwYjQ4NTQ3NGUwNTRkNzI0ZWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uHwAUkG5a_eEqNVlrG8ojYXHC9du0MPPPG_Ywf7VEOE">

Hi @bronzeMe, the question has nothing to do with the title of this issue: "Is there any guide or demos about creating Privileged Enclaves (P-Enclave) and Host User Enclaves (HU-Enclave)?"

Could you please open another new issue to discuss it?

It seems that the your question described by the title "Is there any guide or demos about creating Privileged Enclaves (P-Enclave) and Host User Enclaves (HU-Enclave)?" has been answered. If you agree with this, let us close this issue.
