### ISSUE TITLE
关于架构与Demo问题

### ISSUE THREAD

**Issue by wlstephenw** [HyperEnclave/hyperenclave#18]
我看到论文中的架构是 Rustmonitor上面 启动一个虚拟机，里面运行操作系统和应用程序。但是，在demo中，在安装完hyperenclave之后，并没有重启，直接启动了一个docker。这时候，Rustmonitor与操作系统是平级关系，rustmonitor如何有机会创建于管理enclave呢？

**Comment by xianliang66** [comment]
Hi，启动时Host OS首先跳转到Rustmonitor，Rustmonitor会执行vmentry并把RIP设为Host OS的IP，这样Host OS会运行在低权限Non-root模式而Rustmonitor会运行在高权限Root模式。

**Comment by Bonjourz** [comment]
Hi @wlstephenw , as show in Figure 5(c) in the paper, Rustmonitor runs on the Host mode (Root mode) and untrusted Linux runs on the Guest mode (Non-root mode).

In the HyperEnclave project, after HyperEnclave (Rust monitor) is started (by executing [start_hyperenclave.sh](https://github.com/HyperEnclave/hyperenclave?tab=readme-ov-file#start-hyperenclave)  script), untrusted Linux is demoted into Guest mode while Rustmonitor runs in the Host mode (the highest privilege). In this way, Rustmonitor is able to enforce isolation for all enclaves and untrusted world.

It should be mentioned that the statement:

> 这时候，Rustmonitor与操作系统是平级关系

is not correct.

**Comment by wlstephenw** [comment]
that makes a lot sense to me, thanks for prompt response.
