### ISSUE TITLE
Could you provide an image based on Ubuntu 22.04?

### ISSUE THREAD

**Issue by bronzeMe** [HyperEnclave/hyperenclave#25]
We are attempting to run TEEApps in HyperEnclave. Currently, we can run TEEApps 0.1.0 (an older version based on Ubuntu 20.04) within it. However, the latest [TEEApp](https://github.com/asterinas/trustflow-teeapps) is based on the Ubuntu 22.04 Occlum image, while the image provided by HyperEnclave is still Ubuntu 20.04. In the long term, we hope to run TEEApp 0.3.0 on HyperEnclave. Therefore, we would like to inquire if it is possible to provide a HyperEnclave image based on Ubuntu 22.04? Providing the corresponding Dockerfile would also be acceptable.

**Comment by Bonjourz** [comment]
Hi @bronzeMe ,

This repository has been moved to a new location: https://github.com/asterinas/hyperenclave, and will be will be archived later.

If you such issue still has not been solved, please copy it there: https://github.com/asterinas/hyperenclave/issues, and have a discussion.
