### ISSUE TITLE
Some questions about hyperenclave

### ISSUE THREAD

**Issue by xiaoran33** [HyperEnclave/hyperenclave#28]
Hello, may I inquire about the list of cross platform CPUs supported by hyperenclave in the official: readme document? Do these CPUs need to come with TEE functionality?

**Comment by Bonjourz** [comment]
Hi @xiaoran33 ,

HyperEnclave does not require that CPU is equipped with TEE features. HyperEnclave only relies on the hardware virtualization feature, such as Intel VT-x and AMD-V.

The TEE feature is provided by HyperEnclave software itself by utilizing the virtualization features.

**Comment by xiaoran33** [comment]
Okay, thank you for your answer. Now I have a question to ask: Currently, MySQL can be run directly under Oclum+Hyperenclave; Can MySQL be run directly through a hyperenclave without using Oclum?

**Comment by Bonjourz** [comment]
Hi @xiaoran33 ,

HyperEnclave only provides a TEE environment for users. How to use TEE environment or how to program TEE applications is another topic. 

There are lots of work for running unmodified applications inside SGX-like TEE. So currently, MYSQL can only run with Occlum(LibOS) inside SGX-like TEE without modifications or with minor modifications.

**Comment by xiaoran33** [comment]
好的，感谢解答，再咨询一个问题呢：就是hyperenclave跨平台的问题，readme文档中列出的四种cpu里面，比如要验证mysql在各个cpu上能不能跑起来，都是需要occlum+hyperenclave的方式吗？

**Comment by Bonjourz** [comment]
Hi @xiaoran33 ,

If you want to run them inside HyperEnclave-based TEE, it is suggested that placing MYSQL inside Occlum.

By the way, could you share your purpose in running MYSQL in TEE in different CPUs with us?

**Comment by xiaoran33** [comment]
好的，感谢解答，主要目的：hyperencalve不是列出支持四种厂商的cpu嘛，想通过mysql这个例子，验证一下hyperenclave的跨平台这个特性。

**Comment by xiaoran33** [comment]
> If you want to run them inside HyperEnclave-based TEE, it is suggested that placing MYSQL inside Occlum.

如果不使用occlum呢？

**Comment by Bonjourz** [comment]
Hi @xiaoran33 

I wonder why not use Occlum?
