### ISSUE TITLE
It is stucked after "occlum run"

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/hyperenclave#29]
after "occlum run /bin/hello_world"，It is ok. But another example is stucekd . I use "ps aux" to check the problem，it shows that CPU is full.
 
![image](https://github.com/user-attachments/assets/135628d4-3526-42c6-a333-d745396f9698)

![image](https://github.com/user-attachments/assets/75e485c2-58d6-4e87-ba57-6daab1c44926)

ps aux shows as follows:
![image](https://github.com/user-attachments/assets/5967a8c5-5952-4aa7-9cbd-e58009f5e846)

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 , 

1. Can you successfully run the SGX SDK Samples, by following the [instructions](https://github.com/HyperEnclave/hyperenclave?tab=readme-ov-file#sgx-sdk-samples)?

2. Have you successfully enabled the `wr/rdfsbase` instructions for unprivileged part by following the [instructions](https://github.com/occlum/enable_rdfsbase)?

**Comment by Ariel08081214** [comment]
Hi @Bonjourz
1. Yes，I can run the SGX SDK Samples successfully
2. Yes，`wr/rdfsbase` is enabled 

Maybe the pre-allocated memory is not enough？
![image](https://github.com/user-attachments/assets/8b8ed5fe-7dd4-4a45-b5ee-cbea993509ee)

**Comment by Ariel08081214** [comment]
@Bonjourz I modify the memmap value to 32G，then it works。Now，here is anther question，if the mysql-server run in occlum，how does the outside client connect to it？Waiting for your help

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 

> I modify the memmap value to 32G，then it works

Cool!

> if the mysql-server run in occlum，how does the outside client connect to it，how does the outside client connect to it？

HyperEnclave is only responsible for providing TEE environment for applications. How to program applications inside is another topic.

To my understanding, Occlum provides OS's functionality for unmodified applications running inside enclave. In your provided case, Occlum is responsible transfer messages between unmodified applications(MYSQL-server) and components outside(MYSQL-client) via syscall ABIs(read, write, epoll etc.) and POSIX abstraction (socket).

 You may dive deeply into Occlum's source code or discuss it in Occlum's community: [https://github.com/occlum/occlum](https://github.com/occlum/occlum).

**Comment by Ariel08081214** [comment]
Hi @Bonjourz I appreciate it for your reply. I‘ll try to find answer form Occlum official site
