### ISSUE TITLE
Dose AMD have sealing function?

### ISSUE THREAD

**Issue by prz23** [HyperEnclave/hyperenclave#3]
Does the AMD cpu scheme in hyperenclave have sealing function which Intel SGX have?

**Comment by Bonjourz** [comment]
Yes. You can get more details in **Secret key generation** in our [paper](https://www.usenix.org/system/files/atc22-jia-yuekai.pdf).

**Comment by prz23** [comment]
@Bonjourz the paper said "using TPM’s seal operation", but It seems that AMD’s CPU does not have seal operation.

**Comment by Bonjourz** [comment]
@prz23 HyperEnclave relies on both CPU virtualization extension (for isolation) and **TPM (for root of trust)** to co-construct TEE. HyperEnclave cannot work well with CPU alone.
