### ISSUE TITLE
about EPC

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/hyperenclave#30]
Hai. Why does HyperEnclave has EPC ？Who charges EPC management？How does HyperEnclave map the protected memory to EPC？

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 ,

> Why does HyperEnclave has EPC?

HyperEnclave provides abstraction and security guarantees similar to SGX, it has the same reason as SGX does.

> Who charges EPC management?

Untrusted world(Driver) is responsible for the policy of EPC allocation, and trusted world is responsible for manipulating EPC metadata.

> How does HyperEnclave map the the protected memory to EPC?

HyperEnclave restricts untrusted world's access to all EPC. EPC can be only be accessible to its owner if it is allocated for an enclave. Details can be found in HyperEnclave paper and HyperEnclave source code.

**Comment by Ariel08081214** [comment]
Hi @Bonjourz 
> HyperEnclave provides abstraction and security guarantees similar to SGX, it has the same reason as SGX does.

Is "the memory isolation approach" the mainly difference between SGX and HyperEnclave？

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 ,

> Is "the memory isolation approach" the mainly difference between SGX and HyperEnclave？

No.

By the way, this repository has been moved to a new location: https://github.com/asterinas/hyperenclave, and will be will be archived later.

If you such issue still has not been solved, please copy it there: https://github.com/asterinas/hyperenclave/issues, and have a discussion.
