### ISSUE TITLE
HE_ERROR. Please reserve regions with memmap

### ISSUE THREAD

**Issue by Ariel08081214** [HyperEnclave/hyperenclave#35]
Hai.

I had successfully deployed mysql-server by occlum in HyperEnclave. 

Yesterday, the mysql-server inside occlum worked well while it crashed today after I run mysql command `CREATE TABLE` . Maybe it is nothing to do with my actions,I don't know.
Now, when I run scripts ./run_mysql_server.sh I got the following error:

![image](https://github.com/user-attachments/assets/f191a31f-f9e1-4ad5-ab4f-802e7dc68a13)

demsg shows error:

![image](https://github.com/user-attachments/assets/30c8a949-7108-481e-8ec8-8212484b463c)

Any suggestions for that？

**Comment by Bonjourz** [comment]
Hi @Ariel08081214 ,

Follow the HyperEnclave's README: https://github.com/asterinas/hyperenclave/blob/master/README.md, make sure HyperEnclave starts successfully on your platform.

By the way, this repository has been moved to a new location: https://github.com/asterinas/hyperenclave, and will be will be archived later.

Could you please copy it there: https://github.com/asterinas/hyperenclave/issues, and have a discussion?

Thx!
