### ISSUE TITLE
Errors on updating grub configuration

### ISSUE THREAD

**Issue by jiangtao-ucas** [HyperEnclave/hyperenclave#4]
修改/etc/default/grub后，执行sudo update-grub出现该报错。

**Comment by cz-chenzhou** [comment]
This means command no5lvl isn't found. You should append the configurations for GRUB_CMDLINE_LINUX to the double quotes. 
For example, the old configurations is ```GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8"```,  after update, the configurations should be ```GRUB_CMDLINE_LINUX="console=tty0 console=ttyS0,115200n8 memmap=4G\\\$0x100000000 intel_iommu=off intremap=off no5lvl"```

**Comment by jiangtao-ucas** [comment]
Oh thanks, I appended the configurations after the double quotes before, now I move the configurations into the double quotes and it runs.
Appreciate for your help~
