### ISSUE TITLE
`$ bash start_hyperenclave.sh` error

### ISSUE THREAD

**Issue by jiangtao-ucas** [HyperEnclave/hyperenclave#5]
$ bash start_hyperenclave.sh 
sysctl: cannot stat /proc/sys/dev/hyper_enclave/enabled: No such file or directory
rmmod: ERROR: Module hyper_enclave is not currently loaded
insmod: ERROR: could not load module ../../hyperenclave-driver/driver/hyper_enclave.ko: No such file or directory
sysctl: cannot stat /proc/sys/dev/hyper_enclave/enabled: No such file or directory

$ uname -a
Linux ubuntu 5.15.0-82-generic #91~20.04.1-Ubuntu SMP Fri Aug 18 16:24:39 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/issue
Ubuntu 20.04.6 LTS \n \l

$  cat /proc/cpuinfo | grep name | cut -f2 -d: | uniq -c
      6  Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz

**Comment by cz-chenzhou** [comment]
Please refer to [supported-linux-kernel-version](https://github.com/HyperEnclave/hyperenclave#supported-linux-kernel-version) and install Linux kernel 5.4.
