### ISSUE TITLE
Can HyperEnclave run on Loongson platform? Is that possible to transplant?

### ISSUE THREAD

**Issue by jiangtao-ucas** [HyperEnclave/hyperenclave#8]
I am trying to run HyperEnclave on [loongson](https://github.com/loongson) platform which is using [LoongArch](https://www.loongson.cn/system/loongarch)  architecture. Sorry for the question but I really can't figure out whether it is possible. Thank you for your time!

**Comment by Unik-lif** [comment]
Hyperenclave is based on x86 now, some mechanisms like NPT/EPT specified for x86 are involved, maybe LoongArch now have some similar hardware that can support the relative features, so basically some modifications for the driver as well as the rust-monitor are necessary.

**Comment by jt0129** [comment]
> Hyperenclave is based on x86 now, some mechanisms like NPT/EPT specified for x86 are involved, maybe LoongArch now have some similar hardware that can support the relative features, so basically some modifications for the driver as well as the rust-monitor are necessary.

Thanks for your reply. Yeah I will do the necessary modification, and I noticed that HyperEnclave is claimed as "can run on every CPU which has virtualization feature". So here I have a question, which specifically features does HyperEnclave need? Does LoongArch fit the need?
